# Site settings
title: Home
url: "http://raymondlu.github.io/"
baseurl: ""
timezone: Asia/Shanghai
description: >
  Cocos2dx,Unity,iOS/Android,mobile game,Lua/C++/python,Game development

# Your information
github_username: raymondlu
email: raymondlu1105@qq.com
author: Raymond Lu
avatar: "//www.gravatar.com/avatar/886a2cc8b018565483f9a08b511b81ee?d=mm&s=135"
profile: 俗世里迷途小书童，一直后知后觉。

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: raymondlu  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
